# Site settings
title: Arpan Adhikari - Full Stack Developer
description: Programmer, Developer, Entrepreneur.I design and code beautifully simple things, and I love what I do
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: arpan
user_description: Programmer, Developer, Entrepreneur.I design and code beautifully simple things, and I love what I do
user_title: Software Developer
email: arpan_45@outlook.com
twitter_username: arpanadhikari9
github_username:  arpan45
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
